import { StyleSheet } from "react-native";
import { typography } from "./typography";
import { AppThemeColors } from "../types/themeType";
import { scale, isTabletOrXL } from "../utils/responsive";

export const getStyles = (colors: AppThemeColors, isDark: boolean) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.backgroundColorPrimary,
      alignItems: isTabletOrXL ? "center" : "stretch",
      paddingHorizontal: scale(12),
    },
    headerCard: {
      width: "100%",
      maxWidth: 500,
      marginTop: scale(8),
      marginBottom: scale(10),
      paddingHorizontal: scale(4),
      paddingVertical: scale(6),
      backgroundColor: "transparent",
      borderWidth: 0,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: scale(10),
      paddingBottom: scale(10),
    },
    headerTitle: {
      fontSize: scale(18),
      ...typography.medium,
      color: colors.textPrimary,
    },
    headerAction: {
      fontSize: scale(14),
      ...typography.medium,
      color: colors.btnPrimary,
    },
    avatarCard: {
      width: "100%",
      maxWidth: 500,
      marginBottom: scale(14),
      paddingVertical: scale(20),
      alignItems: "center",
      borderRadius: scale(16),
      backgroundColor: colors.surfacePrimary,
      borderWidth: 0.5,
      borderColor: colors.borderPrimary,
    },
    avatarContainer: {
      alignItems: "center",
      justifyContent: "center",
    },
    avatar: {
      width: scale(96),
      height: scale(96),
      alignItems: "center",
      justifyContent: "center",
      borderRadius: scale(48),
      backgroundColor: colors.white,
      borderWidth: 0.5,
      borderColor: colors.btnPrimary,
    },
    addIcon: {
      position: "absolute",
      right: scale(-2),
      bottom: scale(-2),
      backgroundColor: colors.white,
      borderRadius: scale(18),
      padding: scale(5),
      borderWidth: 0.5,
      borderColor: isDark ? colors.btnPrimary : colors.textSecondary,
    },
    formCard: {
      width: "100%",
      maxWidth: 500,
      paddingHorizontal: scale(14),
      paddingTop: scale(14),
      paddingBottom: scale(8),
      borderRadius: scale(16),
      backgroundColor: colors.surfacePrimary,
      borderWidth: 0.5,
      borderColor: colors.borderPrimary,
    },
    field: {
      marginBottom: scale(12),
    },
    inputLabel: {
      fontSize: scale(14),
      marginBottom: scale(6),
      ...typography.medium,
      color: colors.textPrimary,
    },
    input: {
      width: "100%",
      height: scale(48),
      borderColor: colors.borderPrimary,
      borderWidth: 0.5,
      borderRadius: scale(10),
      paddingHorizontal: scale(14),
      fontSize: scale(16),
      ...typography.regular,
      color: colors.textPrimary,
      backgroundColor: colors.backgroundColorPrimary,
      opacity: 0.55,
    },
    editInput: {
      opacity: 1,
    },
    saveContainer: {
      width: "100%",
      maxWidth: 500,
      marginTop: scale(14),
      marginBottom: scale(16),
    },
    button: {
      backgroundColor: colors.btnPrimary,
      borderRadius: scale(10),
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 12,
    },
    buttonText: {
      ...typography.regular,
      color: colors.white,
      fontSize: scale(16),
    },
  });
