import { StyleSheet } from "react-native";
import { typography } from "./typography";
import { moderateScale } from "react-native-size-matters";
import { AppThemeColors } from "../types/themeType";
import { scale } from "../utils/responsive";

export const getStyles = (colors: AppThemeColors, isDark: boolean) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.backgroundColorPrimary,
    },
    container: {
      flex: 1,
      width: "100%",
      maxWidth: 560,
      alignSelf: "center",
      paddingHorizontal: scale(12),
      paddingTop: scale(12),
      backgroundColor: colors.backgroundColorPrimary,
    },
    scrollContent: {
      paddingBottom: scale(24),
    },
    description: {
      paddingTop: 12,
      paddingBottom: 18,
      paddingHorizontal: 12,
      alignItems: "center",
    },
    title: {
      fontSize: scale(27),
      ...typography.medium,
      textAlign: "center",
      color: colors.textPrimary,
      paddingHorizontal: scale(16),
      paddingVertical: scale(6),
    },
    subtitle: {
      fontSize: scale(16),
      ...typography.regular,
      textAlign: "center",
      color: colors.textPrimary,
      borderWidth: 0.5,
      borderColor: colors.btnPrimary,
      borderRadius: scale(14),
      paddingHorizontal: scale(10),
      paddingVertical: scale(6),
    },
    accentText: {
      color: colors.btnPrimary,
      fontSize: 16,
      ...typography.medium,
      letterSpacing: 0.5,
    },
    emotionsContainer: {
      marginTop: 10,
    },
    emotionTitle: {
      fontSize: scale(18),
      ...typography.medium,
      textAlign: "center",
      color: colors.textPrimary,
    },
    emotions: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "center",
      alignItems: "center",
    },
    emotionButton: {
      width: scale(100),
      minHeight: scale(95),
      justifyContent: "center",
      alignItems: "center",
      paddingVertical: scale(8),
      margin: scale(4),
    },
    emotionActiveButton: {
      width: scale(100),
      minHeight: scale(95),
      justifyContent: "center",
      alignItems: "center",
      paddingVertical: scale(8),
      borderRadius: scale(14),
      margin: scale(4),
      borderWidth: 0.5,
      borderColor: colors.btnPrimary,
    },
    emoji: {
      fontSize: scale(36),
      paddingHorizontal: scale(8),
      paddingVertical: scale(2),
    },
    emotionLabel: {
      textAlign: "center",
      marginTop: scale(4),
      fontSize: scale(12),
      ...typography.regular,
      color: colors.textPrimary,
      paddingHorizontal: 2,
    },
    statistics: {
      width: "100%",
      borderRadius: scale(16),
      padding: scale(16),
      marginTop: scale(18),
      backgroundColor: colors.surfacePrimary,
      borderWidth: 0.5,
      borderColor: colors.borderPrimary,
    },
    statisticsHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: scale(14),
      borderStartColor: colors.surfacePrimary,
    },
    navIconButton: {
      width: scale(28),
      height: scale(28),
      borderRadius: scale(14),
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 0.7,
      borderColor: colors.btnPrimary,
      backgroundColor: "transparent",
    },
    statisticsTitle: {
      fontSize: scale(18),
      ...typography.medium,
      color: colors.textPrimary,
    },
    statisticsContent: {
      gap: scale(8),
    },
    currentEmotion: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: scale(8),
      paddingHorizontal: scale(8),
      borderRadius: scale(10),
      backgroundColor: colors.backgroundColorPrimary,
      borderWidth: 0.5,
      borderColor: colors.dividerPrimary,
    },
    currentEmotionEmoji: {
      fontSize: scale(24),
    },
    currentEmotionLabel: {
      fontSize: scale(15),
      ...typography.regular,
      marginLeft: scale(8),
      color: colors.textPrimary,
    },
    timeContainer: {
      justifyContent: "flex-end",
      flex: 1,
      paddingRight: scale(4),
    },
    currentEmotionTime: {
      textAlign: "right",
      fontSize: scale(13),
      ...typography.regular,
      color: colors.textPrimary,
      opacity: 0.75,
    },
    statisticsEmpty: {
      alignItems: "center",
      paddingVertical: scale(8),
      gap: scale(10),
    },
    emptyTitle: {
      fontSize: scale(15),
      ...typography.regular,
      textAlign: "center",
      color: colors.textPrimary,
    },
    emptySubtitle: {
      fontSize: scale(14),
      ...typography.regular,
      textAlign: "center",
      color: colors.textPrimary,
      opacity: 0.8,
    },
    deleteButton: {
      height: moderateScale(48),
      alignItems: "center",
      justifyContent: "center",
      width: moderateScale(76),
      backgroundColor: colors.btnWarning,
      borderRadius: scale(10),
    },
    deleteButtonText: {
      color: colors.white,
      ...typography.regular,
    },
  });
