import { StyleSheet } from "react-native";
import { ThemeColors, shadow } from "../constants/theme";
import { typography } from "./typography";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 12,
    backgroundColor: ThemeColors.backgroundColorPrimary,
  },
  scrollContent: {
    paddingBottom: 24,
  },
  description: {
    paddingTop: 54,
    paddingBottom: 18,
    paddingHorizontal: 12,
    alignItems: "center",
  },
  title: {
    fontSize: 28,
    ...typography.semiBold,
    marginBottom: 4,
    textAlign: "center",
    color: ThemeColors.textPrimary,
    paddingHorizontal: 16,
    paddingVertical: 6,
  },
  subtitle: {
    fontSize: 16,
    ...typography.regular,
    textAlign: "center",
    color: ThemeColors.textPrimary,
    borderWidth: 0.7,
    borderColor: ThemeColors.btnPrimary,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 7,
  },
  emotionsContainer: {
    marginTop: 20,
  },
  emotionTitle: {
    fontSize: 18,
    ...typography.semiBold,
    textAlign: "center",
    color: ThemeColors.textPrimary,
    marginBottom: 10,
  },
  emotions: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    alignItems: "center",
    gap: 4,
  },
  emotionButton: {
    width: 70,
    alignItems: "center",
    paddingVertical: 10,
    margin: 4,
  },
  emotionActiveButton: {
    width: 70,
    alignItems: "center",
    paddingVertical: 10,
    borderRadius: 14,
    margin: 4,
    backgroundColor: "transparent",
    borderWidth: 0.9,
    borderColor: ThemeColors.btnPrimary,
  },
  emoji: {
    fontSize: 30,
    backgroundColor: ThemeColors.white,
    borderWidth: 0.5,
    borderColor: ThemeColors.dividerPrimary,
    borderRadius: 16,
    paddingHorizontal: 8,
    paddingVertical: 4,
    ...shadow,
  },
  emotionLabel: {
    marginTop: 4,
    fontSize: 13,
    ...typography.regular,
    color: ThemeColors.textPrimary,
  },
  statistics: {
    width: "100%",
    borderRadius: 16,
    padding: 16,
    marginTop: 18,
    backgroundColor: ThemeColors.surfacePrimary,
    borderWidth: 0.5,
    borderColor: ThemeColors.borderPrimary,
    ...shadow,
  },
  statisticsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
    borderStartColor: ThemeColors.surfacePrimary,
  },
  navIconButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 0.7,
    borderColor: ThemeColors.btnPrimary,
    backgroundColor: "transparent",
  },
  statisticsTitle: {
    fontSize: 16,
    ...typography.semiBold,
    color: ThemeColors.textPrimary,
  },
  statisticsContent: {
    gap: 8,
  },
  currentEmotion: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderRadius: 10,
    backgroundColor: ThemeColors.white,
    borderWidth: 0.8,
    borderColor: ThemeColors.dividerPrimary,
  },
  currentEmotionEmoji: {
    fontSize: 24,
  },
  currentEmotionLabel: {
    fontSize: 15,
    ...typography.regular,
    marginLeft: 8,
    color: ThemeColors.textPrimary,
  },
  timeContainer: {
    justifyContent: "flex-end",
    flex: 1,
    paddingRight: 4,
  },
  currentEmotionTime: {
    textAlign: "right",
    fontSize: 13,
    ...typography.regular,
    color: ThemeColors.textPrimary,
    opacity: 0.75,
  },

  statisticsEmpty: {
    alignItems: "center",
    paddingVertical: 28,
    gap: 10,
  },
  emptyTitle: {
    fontSize: 15,
    ...typography.semiBold,
    textAlign: "center",
    color: ThemeColors.textPrimary,
  },
  emptySubtitle: {
    fontSize: 14,
    ...typography.regular,
    textAlign: "center",
    color: ThemeColors.textPrimary,
    opacity: 0.8,
  },
});
